name: Expo EAS Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  eas_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install EAS CLI
        run: npm install -g eas-cli
      - name: EAS Build (Android)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --non-interactive --profile production
